idf_component_register(SRCS "main.c"
                            "bsp.c"
                            "wifi_manager.c"
                            "bt_manager.c"
                            "qmi8658.c"
                            "ui_menu.c"
                            "ui_textinput.c"
                            "tools.c"
                            "tools/tool_clock.c"
                            "tools/tool_wifi.c"
                            "tools/tool_bt.c"
                            "tools/tool_level.c"
                            "tools/tool_gyro.c"
                            "tools/tool_dice.c"
                            "tools/tool_flashlight.c"
                            "tools/tool_wifiscan.c"
                            "tools/tool_netinfo.c"
                       INCLUDE_DIRS ".")
